Cpatcha
scbd/www.cbd.int pull request #494
Opened 2021-04-28 01:28 UTC by blaisefonseca

2021-04-28 13:19 UTC, sbilodeau commented on app/template-2011.ejs
> +    <script src="https://www.google.com/recaptcha/api.js"></script>
Preferable to use `www.recaptcha.net` everywhere (https://www.recaptcha.net/recaptcha/api.js) instead for china (which works
https://www.webpagetest.org/result/210428_AiDc67_da0c1927fb76d9a88de7a9507113960b/)

2021-04-28 13:19 UTC, sbilodeau commented on app/template.ejs
> +    <script src="https://www.google.com/recaptcha/api.js"></script>
Preferable to use `www.recaptcha.net`

2021-04-28 13:19 UTC, sbilodeau commented on app/views/biodiversity-day/customize.js
> +            });
maybe we should make this part of the template? and accesible by env vars & value  provider?
## template
```html

<element captcha-site-key-2="<%=myV2key%>" captcha-site-key-v3="<%=myV3key%> </element>

OR
<script> 
  window.captchaSiteKey2 = "<%=myV2key%>";
  window.captchaSiteKey3 = "<%=myV3key%>";
</script>
```

##App.js
```javascript
app.value("captchaSiteKey2", window.captchaSiteKey2) 
app.value("captchaSiteKey3", window.captchaSiteKey3) 

// OR 

app.value("captchaSiteKey2", $('element').attr('captcha-site-key-2'));
app.value("captchaSiteKey3", $('element').attr('captcha-site-key-3'));
```

finally where you need it

## my view/directive
```javascript
export default ['$location', '$http', ..., captchaSiteKey2,  function( $location, $http, ..., captchaSiteKey2) {
  ...
}
```

2021-04-28 15:16 UTC, blaisefonseca commented on app/views/biodiversity-day/customize.js
> +            });
done!

2021-04-28 15:16 UTC, blaisefonseca commented on app/template.ejs
> +    <script src="https://www.google.com/recaptcha/api.js"></script>
done!

2021-04-28 15:16 UTC, blaisefonseca commented on app/template-2011.ejs
> +    <script src="https://www.google.com/recaptcha/api.js"></script>
done!

2021-04-28 15:20 UTC, randyhoulahan approved these changes

2021-04-28 19:32 UTC, sbilodeau requested changes

2021-04-28 19:32 UTC, sbilodeau commented on app/template-2011.ejs
> +    <element captcha-site-key-2="<%=captchaV2key%>" captcha-site-key-v3="<%=captchaV3key%>"> </element>
I think you should put the attributes on the body. `element` seems not safe. (it was AN EXAPLE)

2021-04-29 15:05 UTC, sbilodeau approved these changes

2021-04-29 15:05 UTC, merged