Feature/nodes angular vue
scbd/www.cbd.int pull request #518
Opened 2021-06-29 09:41 UTC by JamesSCBD

2021-07-15 13:52 UTC, sbilodeau requested changes

2021-07-15 13:52 UTC, sbilodeau commented on app/components/decisions/view-element.vue
> +                        UNEP/CBD/COP/DEC/{{romans[node.session]}}/{{node.decision}}
this will be added to decision. will be `decision.symbol`

2021-07-15 13:52 UTC, sbilodeau commented on app/components/decisions/view-element.vue
> +        }
if text id null or undefined that result string will be 'null' / 'uindefined'

better to
```javascript
(text??'').toString()...
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator

2021-07-15 13:52 UTC, sbilodeau commented on app/components/decisions/view-element.vue
> +            if(node.type === 'information') node.type = 'informational';
this is a bug I will fix from server
```suggestion
```

2021-07-15 13:52 UTC, sbilodeau commented on app/components/references/document-files.vue
> +import MIMES from '~/components/file-type.js';
rename file-type.js => file-types.js
move files to `~/data/`
change all references

2021-07-15 13:52 UTC, sbilodeau commented on app/components/references/meeting-card-list.vue
> +        <!-- TODO - need to remove card for Single Meeting -->
what this mean?

2021-07-15 13:52 UTC, sbilodeau commented on app/components/references/notification-card-list.vue
> +}
import from `~/utisl/solr` instead

2021-07-15 13:52 UTC, sbilodeau commented on app/views/decisions/list.js
> +                $scope.decisions.forEach(function(d){
Need to load from the new API endpoint

2021-07-15 13:52 UTC, sbilodeau commented on app/views/decisions/list.js
> +            return output;
Can use _.padStart

```suggestion
            return _.padStart(input ?? '').toString(), 2, 0);
```

2021-07-15 13:52 UTC, sbilodeau commented on app/views/decisions/view.html
> +    				<b ng-if="newDecision">UNEP/CBD/COP/DEC/{{::newDecision.session}}/{{::newDecision.decision}}</b>
use decision.symbol 
```suggestion
    				<b ng-if="newDecision">{{decision.symbol}}</b>
```

2021-07-15 13:52 UTC, sbilodeau commented on app/views/decisions/view.html
> +					<h3>{{::newDecision.title.en}}</h3>
use lstring filter
```suggestion
					<h3>{{::newDecision.title | lstring}}</h3>
```

2021-07-26 06:47 UTC, JamesSCBD commented on app/views/decisions/list.js
> +                $scope.decisions.forEach(function(d){
I think its not require now as we replace this with vue component.

2021-07-26 07:32 UTC, JamesSCBD commented on app/components/decisions/view-element.vue
> +                        UNEP/CBD/COP/DEC/{{romans[node.session]}}/{{node.decision}}
Done ! currently node.symbol is not coming so kept it has {{node.symbol || 'TODO'}}

2021-07-26 07:32 UTC, JamesSCBD commented on app/components/decisions/view-element.vue
> +                        :href="`/decisions/cop/${node.session}/${node.decision}/${node.section | lowercase}${node.paragraph}${node.item && ('.'+node.item)}`"
Done !

2021-07-26 07:32 UTC, JamesSCBD commented on app/components/decisions/view-element.vue
> +        }
Done!

2021-07-26 07:33 UTC, JamesSCBD commented on app/components/decisions/view-element.vue
> +            if(node.type === 'information') node.type = 'informational';
Removed

2021-07-26 07:33 UTC, JamesSCBD commented on app/components/references/document-files.vue
> +import MIMES from '~/components/file-type.js';
moved files and their references.

2021-07-26 07:33 UTC, JamesSCBD commented on app/components/references/meeting-card-list.vue
> +        <!-- TODO - need to remove card for Single Meeting -->
its was just useless comment. So, removed

2021-07-26 07:33 UTC, JamesSCBD commented on app/components/references/notification-card-list.vue
> +}
Done!

2021-07-26 07:34 UTC, JamesSCBD commented on app/data/decisions/text-info.json
> +]
Deleted

2021-07-26 07:34 UTC, JamesSCBD commented on app/views/decisions/view.html
> +    				<b ng-if="newDecision">UNEP/CBD/COP/DEC/{{::newDecision.session}}/{{::newDecision.decision}}</b>
Done ! currently decision.symbol is not coming so kept it has {{node.symbol || 'TODO'}}

2021-07-26 07:34 UTC, JamesSCBD commented on app/views/decisions/view.html
> +					<h3>{{::newDecision.title.en}}</h3>
Done!

2024-11-20 14:35 UTC, closed without merging