Info note
scbd/www.cbd.int pull request #557
Opened 2022-08-11 20:27 UTC by blaisefonseca

2022-08-11 20:59 UTC, sbilodeau requested changes
Missing seme `ecodeURIComponent`.
Query is passed as function props instead of value/object not best pratice

2022-08-11 20:59 UTC, sbilodeau commented on app/api/articles.js
> +    return this.http.get(`api/v2017/articles/grouping/${groupKey}`, { params })
`encodeURIComponent` GroupKey

2022-08-11 20:59 UTC, sbilodeau commented on app/api/articles.js
> +    return this.http.get(`api/v2017/articles/${id}`)
EncodeURI Component the `id`

2022-08-11 20:59 UTC, sbilodeau commented on app/directives/articles/cbd-add-new-article.vue
> +                                     '&returnUrl=' + window.location.href;
Missing the `encodeURIComponent` for returlUrl value

2022-08-11 20:59 UTC, sbilodeau commented on app/directives/articles/cbd-article.vue
> +import('css!https://cdn.cbd.int/@scbd/ckeditor5-build-inline-full@22.0.0/build/ckeditor.css');
There is as `cdn!` requirejs plugin

2022-08-11 20:59 UTC, sbilodeau commented on app/directives/articles/cbd-article.vue
> +                this.$emit('onLoad', { ...this.article });
what it the purpose of this event?

2022-08-11 20:59 UTC, sbilodeau commented on app/directives/articles/articles-accordion.vue
> +        query: { type: Function, required: true }
not good practice to pass function as prop. should be object+watcher

2022-08-11 20:59 UTC, sbilodeau commented on app/directives/articles/cbd-article.vue
> +        tokenReader     : { type: Function, required: false },
not needed anymore I guess
```suggestion
```

2022-08-11 20:59 UTC, sbilodeau commented on app/views/conferences/info-note.vue
> +        },
not needted anymore I guess
```suggestion
```

2022-08-11 20:59 UTC, sbilodeau commented on app/views/conferences/info-note.vue
> +        query (){
why not a computed instead and pass as objetc to child component insetyad of function?

2022-08-11 20:59 UTC, sbilodeau commented on app/views/conferences/info-note.vue
> +        articleQuery(){
why not a computed instead and pass as objetc to child component insetyad of function?

2022-08-11 20:59 UTC, sbilodeau commented on app/directives/articles/cbd-add-new-article.vue
> +                return  `${baseUrl}/articles/${this.id}/edit?${queryString}`;
missin encodeuricomponent

2022-08-12 15:12 UTC, sbilodeau approved these changes

2022-08-12 15:14 UTC, sbilodeau commented on app/directives/articles/articles-accordion.vue
> +            this.articles = this.articles.map(e=>{
```suggestion
            const articles = await this.ArticlesApi.queryArticles(query);
            this.articles = articles.map(e=>{
```

2022-08-12 16:08 UTC, blaisefonseca commented on app/directives/articles/cbd-article.vue
> +                this.$emit('onLoad', { ...this.article });
sometime the parent wants access to the article, for eg. on conference page we display the cover page is different way because of the layout

2022-08-12 16:08 UTC, blaisefonseca commented on app/views/conferences/info-note.vue
> +        },
fixed

2022-08-12 16:08 UTC, blaisefonseca commented on app/views/conferences/info-note.vue
> +        query (){
fixed

2022-08-12 16:08 UTC, blaisefonseca commented on app/views/conferences/info-note.vue
> +        articleQuery(){
fixed

2022-08-12 16:08 UTC, blaisefonseca commented on app/directives/articles/cbd-add-new-article.vue
> +                return  `${baseUrl}/articles/${this.id}/edit?${queryString}`;
fixed

2022-08-12 16:08 UTC, blaisefonseca commented on app/directives/articles/cbd-article.vue
> +        tokenReader     : { type: Function, required: false },
fixed

2022-08-12 16:08 UTC, blaisefonseca commented on app/directives/articles/articles-accordion.vue
> +        query: { type: Function, required: true }
fixed

2022-08-12 16:08 UTC, blaisefonseca commented on app/directives/articles/cbd-article.vue
> +import('css!https://cdn.cbd.int/@scbd/ckeditor5-build-inline-full@22.0.0/build/ckeditor.css');
fixed

2022-08-12 16:09 UTC, blaisefonseca commented on app/directives/articles/cbd-add-new-article.vue
> +                                     '&returnUrl=' + window.location.href;
fixed

2022-08-12 16:09 UTC, blaisefonseca commented on app/api/articles.js
> +    return this.http.get(`api/v2017/articles/grouping/${groupKey}`, { params })
fixed

2022-08-12 16:10 UTC, merged