Virtual table change
scbd/www.cbd.int pull request #565
Opened 2022-10-24 18:34 UTC by blaisefonseca

2022-10-26 18:17 UTC, randyhoulahan approved these changes

2022-10-26 19:11 UTC, sbilodeau requested changes
you regsiter same component 3 times globally

2022-10-26 19:11 UTC, sbilodeau commented on app/views/meetings/index.js
> +            Vue.component('CbdArticle', CbdArticle)
are ou sure it's goo idea?

2022-10-26 19:11 UTC, sbilodeau commented on app/views/meetings/parallel-meetings.js
> +            Vue.component('CbdArticle', CbdArticle)
dbpile resgistration

2022-10-26 19:11 UTC, sbilodeau commented on app/views/virtual-tables/index.js
> +    Vue.component('CbdArticle', CbdArticle)
tripple registration

2022-10-27 14:44 UTC, sbilodeau approved these changes

2022-10-27 14:44 UTC, merged