mobile app fixes
scbd/www.cbd.int pull request #576
Opened 2022-11-16 16:55 UTC by randyhoulahan

2022-11-16 20:03 UTC, sbilodeau requested changes
Droppped some duplicate comde  + simplify rules (easier to read)

2022-11-16 20:03 UTC, sbilodeau commented on server.js
> +
no needed
```suggestion
```

2022-11-16 20:03 UTC, sbilodeau commented on server.js
> +        /^\/conferences\/(.*)\/(.*)\/documents\?(viewOnly\=true|viewOnly)/
use catchall 
```suggestion
        /^\/conferences\/(.*)\/schedules\?viewOnly.*/,
        /^\/conferences\/(.*)\/(.*)\/documents\?viewOnly.*/
```

2022-11-17 14:07 UTC, blaisefonseca commented on server.js
> +    for (const urlRegEx of iframeAllowedUrls)
For your particular case wouldn't just checking query string be better?

2022-11-17 16:48 UTC, blaisefonseca approved these changes

2022-11-17 18:01 UTC, randyhoulahan commented on server.js
> +    for (const urlRegEx of iframeAllowedUrls)
Yes perhaps but then anyone can add the query string on and by pass blocked iframes for any route.  Better maybe just the route.  Neither route or QS is secret.

2022-11-17 18:53 UTC, merged