Decision Tracking Tool vue version
scbd/www.cbd.int pull request #589
Opened 2023-04-19 20:25 UTC by rqk2k

- Views for the new pages
- Upgraded components to use vue.

2023-04-19 20:49 UTC, sbilodeau requested changes

2023-04-19 20:49 UTC, sbilodeau commented on app/components/meetings/api.js
> +  }
this name is wrong. as it only call Index. must be renamed to `getIndex` (or somthing like) OR name it restrric to get notifications (`q:shema_s:notification`)

2023-04-19 20:49 UTC, sbilodeau commented on app/components/references/decision-card.vue
> +        }
not better to use css `text-rasform: uppercase`

2023-04-19 20:49 UTC, sbilodeau commented on app/components/references/meeting-card.vue
> +            const {startDate, endDate, endDatet} = meeting;
endDate`t`?

2023-04-19 20:49 UTC, sbilodeau commented on app/views/decisions/view.html
> +    				<b ng-if="newDecision">UNEP/CBD/COP/DEC/{{::newDecision.session}}/{{::newDecision.decision}}</b>
`UNEP/CBD/COP/DEC/...` is not always the case must the the symbol from the decision.
must be from previsous code

2023-04-19 21:06 UTC, sbilodeau commented on app/views/decisions/view.js
> +                $http.get('/api/v2016/decision-texts', { params : { q: { treaty:treaty.code, body: body, session: session, decision: number }, fo: 1 }, cache:true }),
we have to stop relying on old api, 
this was for upgarde process.

2023-04-19 21:06 UTC, sbilodeau commented on app/views/decisions/view.js
> +        $scope.newDecision = {};
shoudl stop use name `newDecison`

2023-05-01 18:35 UTC, rqk2k commented on app/components/meetings/api.js
> +  }
Issue fixed.

`  async getNotifications(options) {

    const options = {
      
      params : {
          q : `symbol_s (${codes.map(solr.escape).join(' or ')})`,
          fl : "id, symbol_s,reference_s,title_t,date_dt,url_ss",
      }
    }
    const notifications = await api.queryNotifications(options).then(res => res.data).catch(tryCastToApiError);
    return notifications;
  }

  async queryNotifications({q: userQ, ...otherParams}) {
    let q = 'schema_s:notification'

    if(userQ) q = `${q} AND (${userQ})`;

    const params = { ...otherParams, q };

    const notifications = await this.http.get('/api/v2013/index', { params }).then(res => res.data).catch(tryCastToApiError);
    return notifications;
  }
`

2023-05-01 19:10 UTC, rqk2k commented on app/components/meetings/api.js
> +  }
Issue fixed.

```
  async getDecisions(options) {
    const decisions = await this.http.get('/api/v2021/decisions', options).then(res => res.data).catch(tryCastToApiError);
    return decisions;
  }
```

2023-05-01 19:31 UTC, rqk2k commented on app/components/references/decision-card.vue
> +        }
issue fixed

```
                <span v-if="decision.elements[0]">
                    <span v-if="decision.elements[0].section" class="uppercase">
                        {{ decision.elements[0].section }}
                    </span>
                    <span v-if="decision.elements[0].paragraph">
                        para {{ decision.elements[0].paragraph }}
                    </span>
                    <span v-if="decision.elements[0].item" class="lowercase">
                        {{ decision.elements[0].item }})
                    </span>
                    <span v-if="decision.elements[0].subitem" class="lowercase">
                        {{ decision.elements[0].subitem }})
                    </span>
                </span>
```

```
<style>
.uppercase {
    text-transform: uppercase;
}
.lowercase {
    text-transform: lowercase;
}
</style>
```

2023-05-01 19:50 UTC, rqk2k commented on app/components/references/meeting-card.vue
> +            const {startDate, endDate, endDatet} = meeting;
issue fixed. Replaced references for endDatet to endDate.

2023-05-01 19:56 UTC, rqk2k commented on app/views/decisions/view.html
> +    				<b ng-if="newDecision">UNEP/CBD/COP/DEC/{{::newDecision.session}}/{{::newDecision.decision}}</b>
This code refers to the old version of the DTT.

2023-05-01 19:57 UTC, rqk2k commented on app/views/decisions/view.js
> +                $http.get('/api/v2016/decision-texts', { params : { q: { treaty:treaty.code, body: body, session: session, decision: number }, fo: 1 }, cache:true }),
Same as the previous comments, this code refers to the old version of the DTT.

2023-05-02 18:49 UTC, sbilodeau requested changes
I think the update for getNotifcation was nett implemented correctly

2023-05-02 18:49 UTC, sbilodeau commented on app/api/decisions.js
> +  }
this is query index.

shouldonly passe porbaly a decision code and it return the docu,mtns

2023-05-02 18:49 UTC, sbilodeau commented on app/components/decisions/decision-view-help.vue
> +		<a href="javascript:void(0)" @click="startTour">{{title}}</a>
dont use `javascript:void(0)`

```suggestion
		<a href="#" @click.prevent="startTour">{{title}}</a>
```

2023-05-02 18:49 UTC, sbilodeau commented on app/components/decisions/decision-search-help.vue
> +		<a href="javascript:void(0)" @click="startTour">{{title}}</a>
dont use `javascript:void(0)`
```suggestion
		<a href="#" @click.prevent="startTour">{{title}}</a>
```

2023-05-02 18:49 UTC, sbilodeau commented on app/components/decisions/edit-element.vue
> +            :class="nodeComments.length > 0 && 'has-comments'"
nice hack!

2023-05-02 18:49 UTC, sbilodeau commented on app/components/meetings/api.js
> +  }
passing options directo to http library is bad. shoudl rename and change siganture
eg: 
```suggestion
  async queryMeetingDocuments({cache, ...params} ) {
  // params: { q, f, l, sk, fo } 
  
  cache = !!cache; // force boolean
  
    const documents = await this.http.get(`/api/v2016/documents`, { params, cache }).then(res => res.data).catch(tryCastToApiError);
    return documents;
  } 
```

2023-05-02 18:49 UTC, sbilodeau commented on app/components/meetings/api.js
> +  }
same ad for queryMeetingDocuments   

```suggestion
  async queryMeetings({cache, ...params} ) {
  
  cache = !!cache; // force boolean. default false
  
    const meetings = await this.http.get(`/api/v2016/meetings`, { params, cache }).then(res => res.data).catch(tryCastToApiError);
    return meetings;
  }
```

2023-05-02 18:49 UTC, sbilodeau commented on app/components/meetings/api.js
> +  }
Delete this artifact and it contains errors

* `options` passed is ignored
* `codes` is undefined
* queryNotifications accepts {`q,`fl`, `etc`} fields not `params` not 
I thing must call qieryNotification from your user code

2023-05-02 18:49 UTC, sbilodeau commented on app/components/meetings/api.js
> +  }
You can add option to cache the cache result

utilmatly you should return only the records parrt from index


```suggestion
  async queryNotifications({q: userQ, cache,  ...otherParams}) {
  
  cache = !!cache;
    let q = 'schema_s:notification'

    if(userQ) q = `${q} AND (${userQ})`;

    const params = { ...otherParams, q };

    const res = await this.http.get('/api/v2013/index', { params, cache }).then(res => res.data).catch(tryCastToApiError);
    return res;
  }
```

```javascript

    const res = await this.http.get('/api/v2013/index', { params, cache }).then(res => res.data).catch(tryCastToApiError);
    return res.response.docs;

```

2023-05-02 18:49 UTC, sbilodeau commented on app/components/meetings/api.js
> +  }
same as for queryMeetingDocuments. Don't pass option to be apply directly to the http library but pass parameters to filter your quer. you can have controlled option (eg cache)
```suggestion
  async queryDecisions({ cache, ...params}) {
  cache = !!cache;//force bool
    const decisions = await this.http.get('/api/v2021/decisions', { params, cache }).then(res => res.data).catch(tryCastToApiError);
    return decisions;
  }
```

2023-05-02 18:49 UTC, sbilodeau commented on app/components/references/decision-card-list.vue
> +    const results = await this.api.getDecisions(options);
see my comment about change getDecisions=>queryDecisions

2023-05-02 18:49 UTC, sbilodeau commented on app/components/meetings/api.js
> +    const decisions = await this.http.get('/api/v2021/decisions', options).then(res => res.data).catch(tryCastToApiError);
is `/api/v2021/decision` the new endpoint?

2023-05-02 18:49 UTC, sbilodeau commented on app/components/references/meeting-card-list.vue
> +    const res = await this.api.getMeetings(options);
see my comment aboit getMeetingd=>queryMeetings

2023-05-02 18:49 UTC, sbilodeau commented on app/components/references/meeting-document-card-list.vue
> +    return documents;
see my comment qabout getMeetingDocument=>queryMeetingDocuments

2023-05-02 18:49 UTC, sbilodeau commented on app/components/references/notification-card.vue
> +        <i v-if="notification.number">({{ notification.number }})</i>
I think the symbol and number must be reversed. `symbol` is the maillog id while the number is the unique Notification ID. number if the offcicial notification identifier (format is ####-###. eg 2023-017)
as two notiiciation can have the same maillog id but not the same number

2023-05-02 18:49 UTC, sbilodeau commented on app/views/decisions/decision-view.vue
> +		throw 'ONLY "COP" DECISIONS ARE SUPPORTED';
I know 😢

2023-05-02 19:22 UTC, rqk2k commented on app/views/decisions/decision-view.vue
> +		throw 'ONLY "COP" DECISIONS ARE SUPPORTED';
The new version will support the other ones. ;-)

2023-05-02 19:39 UTC, rqk2k commented on app/views/decisions/decision-view.vue
> +		throw 'ONLY "COP" DECISIONS ARE SUPPORTED';
The new version will solve this problem. :-)

2023-05-02 19:40 UTC, rqk2k commented on app/components/decisions/decision-search-help.vue
> +		<a href="javascript:void(0)" @click="startTour">{{title}}</a>
Issue solved. All instances of `javascript:void(0)` have been replaced with `@click.prevent`.

2023-05-02 19:55 UTC, rqk2k commented on app/components/references/meeting-card-list.vue
> +            symbol:    m.EVT_CD || m.symbol,
issue fixed.

2023-05-10 17:40 UTC, rqk2k commented on app/api/decisions.js
> +  }
It was fixed, now the request goes directly to the queryDecisionDocuments.

2023-05-11 13:51 UTC, rqk2k commented
> 

It was fixed now.

2023-05-11 16:05 UTC, rqk2k commented on app/components/meetings/api.js
> +  }
The issue was fixed.

2023-05-11 16:05 UTC, rqk2k commented on app/components/references/meeting-document-card-list.vue
> +    return documents;
Issue was fixed.

2023-05-11 17:39 UTC, rqk2k commented on app/components/meetings/api.js
> +  }
Since getMeetings is being used somewhere else, I created a new function called queryMeetings using the same concept as applied on the queryMeetingDocuments.

2023-05-11 17:46 UTC, rqk2k commented on app/components/meetings/api.js
> +  }
This code is outdated, the new version has been deployed. Can you revise it?

2023-05-11 18:00 UTC, rqk2k commented on app/components/meetings/api.js
> +  }
Cache included and issue with q and fl fixed.

2023-05-11 18:07 UTC, rqk2k commented on app/components/references/decision-card-list.vue
> +    const results = await this.api.getDecisions(options);
Issue fixed.

2023-05-11 18:19 UTC, rqk2k commented on app/components/meetings/api.js
> +  }
function getDecisions removed from api.js

2023-05-11 18:44 UTC, rqk2k commented on app/components/references/notification-card-list.vue
> +    const results = _.map(res.response.docs, function(n) {
Issue fixed.

2023-05-11 19:11 UTC, rqk2k commented on app/components/references/notification-card.vue
> +        <i v-if="notification.number">({{ notification.number }})</i>
Should it be this way?

`<b v-if="notification.number">({{ notification.number }})</b>
<i>{{ notification.symbol }}</i>`

2023-05-11 19:20 UTC, sbilodeau commented on app/components/references/notification-card.vue
> +        <i v-if="notification.number">({{ notification.number }})</i>
should apper like this:

> **2021-023** _Aht/KG/23/WDY/3_

2023-05-11 19:33 UTC, rqk2k commented on app/components/references/decision-card.vue
> +                        {{ decision.elements[0].subitem }})
As discussed, it seems that it's OK, but I'm marking this to be improved.

2023-05-11 19:54 UTC, rqk2k commented on app/components/references/notification-card.vue
> +        <i v-if="notification.number">({{ notification.number }})</i>
The changed was done, trying to locate a notification to verify.

2023-05-11 21:39 UTC, randyhoulahan approved these changes

2023-05-11 21:39 UTC, randyhoulahan commented on app/components/references/decision-card.vue
> +    filters: {
https://v3-migration.vuejs.org/breaking-changes/filters.html

2023-05-12 17:58 UTC, blaisefonseca requested changes
please see comments

2023-05-12 17:58 UTC, blaisefonseca commented on app/api/decisions.js
> +    let q = 'schema_s:schema_s:(decision recommendation)'
```suggestion
    let q = 'schema_s:(decision recommendation)'
```

2023-05-12 17:58 UTC, blaisefonseca commented on app/components/references/decision-card-list.vue
> +        d.url = '/decisions/'+d.body.toLowerCase()+'/'+d.session+'/'+d.decision;
encodeURIComponent

2023-05-12 17:58 UTC, blaisefonseca commented on app/components/references/notification-card-list.vue
> +    const q = `symbol_s (${codes.map(solr.escape).join(' or ')})`
missing `:` in query
```suggestion
    const q = `symbol_s : (${codes.map(solr.escape).join(' ')})`
```

2023-05-12 17:58 UTC, blaisefonseca commented on app/components/references/notification-card-list.vue
> +            url : 'https://www.cbd.int'+url
better to check if the url is starting with `/` ignore if it starts with `http`

2023-05-12 17:58 UTC, blaisefonseca commented on app/filters/term.js
> +    return cacheMap[term.identifier] = api.http.get("/api/v2013/thesaurus/terms?termCode=" + encodeURIComponent(term.identifier)).then(function (result) {
missing cache:true

2023-05-12 17:58 UTC, blaisefonseca commented on app/views/decisions/decision-view.vue
> +			files : _.map(n.file_ss, function(f){ return JSON.parse(f); }),
why parse a URL?

2023-05-12 17:58 UTC, blaisefonseca commented on app/views/decisions/edit-translation.vue
> +		route: { type: Object, required: false }
this is accessible through vue global object `this.$route` `this.$auth.strategy?.token?.get()`

2023-05-12 17:58 UTC, blaisefonseca commented on app/views/decisions/edit-translation.vue
> +	const code = treaty.acronym+'/'+body+'/'+pad(session)+'/'+pad(number);
encodeURIComponent

2023-05-12 17:58 UTC, blaisefonseca commented on app/views/decisions/edit.js
> +                const code = treaty.acronym+'/'+body+'/'+pad(session)+'/'+pad(decision);
encode

2023-05-12 17:58 UTC, blaisefonseca commented on app/views/decisions/list.js
>                  return $http.get('/api/v2015/treaties/'+treaty.code, { cache: true } );
encode

2023-05-17 18:25 UTC, rqk2k commented on app/components/references/decision-card.vue
> +    filters: {
Noted, will keep this for updated on the next version.

2023-05-17 18:27 UTC, rqk2k commented on app/api/decisions.js
> +    let q = 'schema_s:schema_s:(decision recommendation)'
Issue fixed.

2023-05-17 18:29 UTC, rqk2k commented on app/components/references/notification-card-list.vue
> +    const q = `symbol_s (${codes.map(solr.escape).join(' or ')})`
Issue fixed.

2023-05-23 15:18 UTC, rqk2k commented on app/views/decisions/edit.js
> +                const code = treaty.acronym+'/'+body+'/'+pad(session)+'/'+pad(decision);
issue solved.

2023-05-23 15:20 UTC, rqk2k commented on app/views/decisions/list.js
>                  return $http.get('/api/v2015/treaties/'+treaty.code, { cache: true } );
issue solved.

2023-05-23 15:32 UTC, rqk2k commented on app/filters/term.js
> +    return cacheMap[term.identifier] = api.http.get("/api/v2013/thesaurus/terms?termCode=" + encodeURIComponent(term.identifier)).then(function (result) {
issue solved.

2023-05-23 15:37 UTC, rqk2k commented on app/components/references/decision-card-list.vue
> +        d.url = '/decisions/'+d.body.toLowerCase()+'/'+d.session+'/'+d.decision;
issue solved.

2023-05-26 19:53 UTC, rqk2k commented on app/views/decisions/edit-translation.vue
> +		route: { type: Object, required: false }
I think it wasn't installed at the time this project was started. Needed to be reviewed. (Steph told me that.)

2023-05-26 19:54 UTC, rqk2k commented on app/components/references/notification-card-list.vue
> +            url : 'https://www.cbd.int'+url
Issue solved using new URL as it's a more clean solution.

2023-05-26 20:51 UTC, sbilodeau commented on app/views/decisions/decision-view.vue
> +			files : _.map(n.file_ss, function(f){ return JSON.parse(f); }),
it's because the `file_ss` is from solr and contains a JSON serilized verison of and objrct that needs to be parse to be usable. 

```javascript
file_ss = "{\"_id\":\"620ad22f116da5108e7ed7b1\",\"name\":\"cop-01-dec-04-en.pdf\",\"size\":0,\"type\":\"application/pdf\",\"language\":\"en\",\"url\":\"https://www.cbd.int/doc/decisions/cop-01/cop-01-dec-04-en.pdf\",\"md5\":\"\",\"deleted\":false}"

files = {
  _id: '620ad22f116da5108e7ed7b1',
  name: 'cop-01-dec-04-en.pdf',
  size: 0,
  type: 'application/pdf',
  language: 'en',
  url: 'https://www.cbd.int/doc/decisions/cop-01/cop-01-dec-04-en.pdf',
  md5: '',
  deleted: false
}
```

2023-06-02 15:40 UTC, sbilodeau commented on app/components/meetings/api.js
> +  }
unsuedunused code please delete
```suggestion
```

2023-06-02 15:41 UTC, sbilodeau commented on app/components/meetings/api.js
> +  */
delet useless code 
```suggestion
```

2023-06-02 15:42 UTC, sbilodeau commented on app/components/references/decision-card-list.vue
> +    */
can we drop?
```suggestion
```

2023-06-02 15:42 UTC, sbilodeau commented on app/components/references/decision-card-list.vue
> +        //d.elements = d.elements.filter(e => e.code === getElementCode(d.code));
drop
```suggestion
```

2023-06-02 15:42 UTC, sbilodeau commented on app/components/references/meeting-card-list.vue
> +    */
drop
```suggestion
```

2023-06-02 15:43 UTC, sbilodeau commented on app/components/references/meeting-card-list.vue
> +    // const res = await this.api.getMeetings(options);
drop
```suggestion
```

2023-06-02 15:48 UTC, sbilodeau requested changes
Dont keep old code in comment. it has no value added and make code more confusing liek if not sure the new code is good. 

we can use `blame` feature of git to go back see what was there before

also delete old unsused `getMettegs(options)` fucntion

2023-06-02 15:48 UTC, sbilodeau requested changes
Dont keep old code in comment. it has no value added and make code more confusing liek if not sure the new code is good. 

we can use `blame` feature of git to go back see what was there before

also delete old unsused `getMettegs(options)` fucntion

2023-06-13 13:35 UTC, rqk2k commented on app/components/meetings/api.js
> +  }
Removed.

2023-06-13 13:36 UTC, rqk2k commented on app/components/meetings/api.js
> +  */
Removed.

2023-06-13 13:38 UTC, rqk2k commented on app/components/references/decision-card-list.vue
> +        //d.elements = d.elements.filter(e => e.code === getElementCode(d.code));
Removed.

2023-06-13 13:38 UTC, rqk2k commented on app/components/references/meeting-card-list.vue
> +    */
Removed.

2023-06-13 13:39 UTC, rqk2k commented on app/components/references/meeting-card-list.vue
> +    // const res = await this.api.getMeetings(options);
Removed.

2023-06-15 18:36 UTC, merged