DEV-510 - Edit permission issue
scbd/www.cbd.int pull request #644
Opened 2024-05-21 15:19 UTC by rqk2k

### General description
Fixing the permission on editing decisions as well as adding new decision tracking editing tagging (GBF targets and Goals) and search using the solr index.

### Designs
N/A

### Testing instructions
- The solr search has been tested and validated on the dev environment using the URL: https://www.cbddev.xyz/decisions/search/
- The tagging functionality has been tested and validaded on the URL: https://www.cbddev.xyz/decisions/cop/15

## Checklist before merging
* [X]  Branch name / PR includes the related Jira ticket Id.
* [-]  Tests to check core implementation / bug fix added. (Has been tested on DEV environment).
* [X]  All checks in Continuous Integration workflow pass.
* [X]  Feature functionally tested by reviewer(s).
* [-]  Code reviewed by reviewer(s). - In progress
* [-]  Documentation updated (README, CHANGELOG...) (if required) (N/A)

2024-05-21 22:25 UTC, randyhoulahan commented on app/data/gbf-targets/goals.json
> +[
why not from the api?

2024-05-21 22:29 UTC, randyhoulahan approved these changes

2024-05-21 22:29 UTC, randyhoulahan commented on app/images/gbf-targets/gbf-23-64.png
are these official?  please share source in ref if i missed it.  I am using a blue unofficial version.

2024-05-21 22:53 UTC, randyhoulahan approved these changes

2024-05-22 13:03 UTC, rqk2k commented on app/data/gbf-targets/goals.json
> +[
This was a old file, the actual page is getting from the API.

2024-05-22 14:21 UTC, sbilodeau requested changes
2-3 comments. please update

2024-05-22 14:21 UTC, sbilodeau commented on app/data/gbf-targets/goals.json
> +[
can you delete?

2024-05-22 14:21 UTC, sbilodeau commented on app/routes/decisions.js
> +    .when('/search',                              { ...mapView(vueViewWrapper),         resolve: { ...decisionSearch, user : currentUser() }, reloadOnSearch : false } )
can you delete the old search at lien #8 and delete the old search files

2024-05-22 14:54 UTC, rqk2k commented on app/routes/decisions.js
> +    .when('/search',                              { ...mapView(vueViewWrapper),         resolve: { ...decisionSearch, user : currentUser() }, reloadOnSearch : false } )
done.

2024-05-22 20:20 UTC, randyhoulahan commented on app/data/gbf-targets/goals.json
> +[
@sbilodeau I assisted here.  Tried to call with axios, created and mounted.  Getting strange error I cannot resolve (quick).  I think it angualar-vue package.  I will put this through then figure out the problem why I can't get axios to work.

2024-05-22 20:20 UTC, merged