DEV-524 media accreditation i18n
scbd/www.cbd.int pull request #647
Opened 2024-06-14 17:36 UTC by randyhoulahan

2024-06-14 18:58 UTC, rqk2k commented on app/directives/kronos/participant.js
> +            $scope.error = { status: 4000 }
4000 or 400?

2024-06-14 18:59 UTC, rqk2k approved these changes

2024-06-14 19:00 UTC, randyhoulahan commented on app/directives/kronos/participant.js
> +            $scope.error = { status: 4000 }
I used a custom number just to show an additional warning to user that form has errors.

2024-06-18 19:50 UTC, sbilodeau requested changes

2024-06-18 19:50 UTC, sbilodeau commented on app/i18n/participation/fr.js
> +    "secretariatCbdInt": "secrétariat@cbd.int",
email value should not be translated 
```suggestion
    "secretariatCbdInt": "secretariat@cbd.int",
```

2024-06-18 19:50 UTC, sbilodeau commented on app/i18n/shared/fr.js
> +  "asb": "Centre d’échange sur l’accès et le partage des avantages",
asb or abs?

2024-06-18 19:50 UTC, sbilodeau commented on app/views/media-requests/participation-form.js
> +      {'identifier':'Other',              'title': $i18n.get(camelCase('Other'), 'participationT') }],
whay not just put the camelCase code instead

2024-06-18 19:50 UTC, sbilodeau commented on app/views/media-requests/participation-form.js
> +      {'identifier':'Other'                                   , 'title': $i18n.get(camelCase('Other') , 'participationT'                                  ) },
make the value camelCased and remove the `camelCase()`

2024-06-18 19:50 UTC, sbilodeau commented on app/views/media-requests/participation-form.js
> +        'application/zip':                                                            { title: $i18n.get(camelCase('Zip'), 'participationT'),               color: '',       btn: 'btn-default', icon:
same... and everywhere else

2024-06-18 19:50 UTC, sbilodeau commented on app/i18n/shared/en.js
> +  "nationalBiodiversityStrategiesAndActionPlansNbsaPs": "National                                    Biodiversity Strategies and Action Plans (NBSAPs)",
fix extras spacing in en original files

2024-06-18 19:50 UTC, sbilodeau commented on app/i18n/participation/index.js
> +import zh from './zh.js';
conveet lang lfiles to JSON and import using assert
```suggestion
import en from './en.json' assert { type: 'json' };
import ar from './ar.json' assert { type: 'json' };
import es from './es.json' assert { type: 'json' };
import fr from './fr.json' assert { type: 'json' };
import ru from './ru.json' assert { type: 'json' };
import zh from './zh.json' assert { type: 'json' };
```

2024-06-18 19:50 UTC, sbilodeau commented on app/i18n/shared/index.js
> +import zh from './zh.js';
```suggestion
import en from './en.json' assert { type: 'json' };
import ar from './ar.json' assert { type: 'json' };
import es from './es.json' assert { type: 'json' };
import fr from './fr.json' assert { type: 'json' };
import ru from './ru.json' assert { type: 'json' };
import zh from './zh.json' assert { type: 'json' };
```

2024-06-19 14:08 UTC, blaisefonseca commented on app/directives/kronos/participant.js
> +                  $scope.$emit('showSuccess', $i18n.get('participantSaved', 'participationT') );
should have used filter instead of changing the fn

2024-06-19 15:31 UTC, randyhoulahan commented on app/directives/kronos/participant.js
> +                  $scope.$emit('showSuccess', $i18n.get('participantSaved', 'participationT') );
Yes, I forgot about $filter.  Thought it was only pipe in the interpolation.  Yet I also defaulted no translation to english instead of key.

2024-06-19 15:48 UTC, randyhoulahan commented on app/directives/kronos/participant.js
> +                  $scope.$emit('showSuccess', $i18n.get('participantSaved', 'participationT') );
Also changes had to be made to load in all in one file, as suggested by. you.

2024-06-20 18:40 UTC, blaisefonseca approved these changes

2024-06-20 18:41 UTC, merged