DEV-539 - Make statement File/Text extract easily aceessible to Interpreters
scbd/www.cbd.int pull request #667
Opened 2024-09-16 15:44 UTC by rqk2k

### General description
Improving accessibility on interpreter screen to allow easy access to text extract for interpreters when using tablet/phone devices.

### Designs
N/A

### Testing instructions
- Access the interpreter panel (https://www.cbddev.xyz/conferences/nairobi-2023/interpreter-panel).
- Next to the download document button, the text extract icon should appear larger with a darker border.
- The icon will change only on this page, on all the other pages the icon will remain as it was before.

## Checklist before merging
* [X]  Branch name / PR includes the related Jira ticket Id.
* [X]  Tests to check core implementation / bug fix added.
* [X]  All checks in Continuous Integration workflow pass.
* [ ]  Feature functionally tested by reviewer(s).
* [ ]  Code reviewed by reviewer(s).
* [X]  Documentation updated (README, CHANGELOG...) (if required)

2024-09-16 15:59 UTC, blaisefonseca commented on app/components/meetings/sessions/files-view.vue
> +            <a @click="showPreview(text, language)" :style="{ visibility: (text?'visible':'hidden') }" :class="{ 'btn': showPreviewAsButton, 'btn-lg': showPreviewAsButton, 'btn-outline-dark': showPre
```suggestion
            <a @click="showPreview(text, language)" :style="{ visibility: (text?'visible':'hidden') }" :class="{ 'btn btn-lg btn-outline-dark': showPreviewAsButton}">
```

2024-09-16 17:44 UTC, blaisefonseca approved these changes

2024-09-16 18:35 UTC, sbilodeau requested changes

2024-09-16 18:35 UTC, sbilodeau commented on app/components/meetings/sessions/files-view.vue
> +              <i :style="{ visibility: (text?'visible':'hidden') }" class="fa fa-file-text-o" aria-hidden="true"></i>
no need to have the visibility style here has it was moved above
```suggestion
              <i class="fa fa-file-text-o" aria-hidden="true"></i>
```

2024-09-17 15:43 UTC, sbilodeau approved these changes

2024-09-17 15:43 UTC, merged